image: gitpod/workspace-full
  # file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  # - port: 3000
  #   onOpen: open-preview
  # - port: 8443
  #   onOpen: open-preview
  - port: 8080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      sudo docker-up &
      sudo scripts/self-signed-certificate.sh
      echo export GHOST_URL=`echo ${GITPOD_WORKSPACE_URL} | sed 's/https:\/\//http:\/\/2368-/g'` >> ${HOME}/.bashrc
      clear >$(tty)
  - command: |
      echo "================================================================================"
      echo "= Hi All, You can use command \"docker-compose up -d\" to to start the service. ="
      echo "= THE GHOST_URL=${GHOST_URL}, HAVE BEEN SET IN ENVIRONMENT VARIABLE ="
      echo "================================================================================"

  # - command: echo "${GITPOD_WORKSPACE_URL}, ${GITPOD_HOST}"


# List the vscode extension.
vscode:
  extensions:
    - pkief.material-icon-theme
    - zhuangtongfa.material-theme
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - editorconfig.editorconfig
