image: gitpod/workspace-full
  # file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 443
    onOpen: open-preview
  - port: 80
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: sudo docker-up

# List the vscode extension.
vscode:
  extensions:
    - pkief.material-icon-theme
    - zhuangtongfa.material-theme
    - esbenp.prettier-vscode