version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    hostname: nginx
    ports:
      # - 443:443
      # - 80:80
      # - 8443:443
      - 8080:80
    volumes:
      # - ${PWD}/nginx/ssl/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key:ro
      # - ${PWD}/nginx/ssl/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt:ro
      - ${PWD}/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - front_end
    depends_on:
      - ghost
    restart: always

  ghost:
    image: ghost:alpine
    container_name: ghost
    hostname: ghost
    volumes:
      # - ${PWD}/ghost/config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings 
      - ${PWD}/ghost/content:/var/lib/ghost/content:z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment: # this section can be commented to start in dev mode by default
      - NODE_ENV=production # set either production or development, then it will load the respective config
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=ghostusr
      - database__connection__password=ghostpasswd
      - database__connection__database=ghostdata
      - url="${GHOST_URL}"
    restart: always
    ports: 
      - '2368:2368'
    networks:
      - front_end
      - back_end
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
       - ${PWD}/dbdata:/var/lib/mysql:z  # Persist storage
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
    environment:
      # Beware of special characters in password that can be interpreted by shell
      - MYSQL_ROOT_PASSWORD=toor #specify your root pass
      - MYSQL_DATABASE=ghostdata
      - MYSQL_USER=ghostusr
      - MYSQL_PASSWORD=ghostpasswd #please change this
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--skip-character-set-client-handshake"]
    networks:
      - back_end
    restart: always

# #########################################################################
# Default network driver: Bridge mode
# #########################################################################
networks:
  front_end:
  back_end:
    